; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32@^6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000L
board_build.psram = disable
lib_deps = 
	bblanchon/ArduinoJson@^7.2.0
	knolleary/PubSubClient@^2.7
build_type = release
build_flags = 
	-Wall
	-DFW_VERSION=\"1.0.0\"
	-DARDUINOJSON_ENABLE_PROGMEM=0

; I2C 扫描环境（用于查找 MPU6500 传感器）
[env:scanner]
platform = espressif32@^6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000L
board_build.psram = disable
src_filter =
    +<*.cpp>
    -<main.cpp>
    +<i2c_scanner.cpp>
